<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Customers Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #333;
        }

        h1 {
            text-align: center;
            margin-bottom: 5px;
            font-size: 22px;
        }

        .subtitle {
            text-align: center;
            margin-bottom: 20px;
            color: #777;
            font-size: 10px;
        }

        .meta {
            margin-bottom: 15px;
            font-size: 11px;
            color: #666;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        thead {
            background: #f3f4f6;
        }

        th,
        td {
            border: 1px solid #d1d5db;
            padding: 8px 6px;
            text-align: left;
            vertical-align: top;
        }

        th {
            font-size: 10px;
            font-weight: bold;
        }

        td {
            font-size: 9px;
        }

        tbody tr:nth-child(even) {
            background: #f9fafb;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .vip {
            color: #059669;
            font-weight: bold;
        }

        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 9px;
            color: #888;
        }
    </style>
</head>

<body>

    <h1>Customers Report</h1>

    <div class="subtitle">
        Generated on {{ now()->format('F d, Y h:i A') }}
        @if($roleFilter !== 'all')
            | Filter: {{ ucfirst($roleFilter) }}
        @endif
    </div>

    <div class="meta">
        Total Customers: <strong>{{ $totalCustomers }}</strong> |
        Active Customers: <strong>{{ $activeCustomers }}</strong> |
        VIP Members: <strong>{{ $vipMembers }}</strong> |
        Total Records: <strong>{{ $customers->count() }}</strong>
    </div>

    <table>
        <thead>
            <tr>
                <th width="5%">ID</th>
                <th width="18%">Name</th>
                <th width="20%">Email</th>
                <th width="12%">Phone</th>
                <th width="8%">Role</th>
                <th width="8%" class="text-center">Orders</th>
                <th width="12%" class="text-right">Total Spent</th>
                <th width="7%" class="text-center">VIP</th>
                <th width="10%">Joined</th>
            </tr>
        </thead>

        <tbody>
            @forelse($customers as $customer)
                <tr>
                    <td>{{ $customer->id }}</td>
                    <td>{{ $customer->name }}</td>
                    <td>{{ $customer->email ?: '-' }}</td>
                    <td>{{ $customer->phone ?: '-' }}</td>
                    <td>{{ ucfirst($customer->role) }}</td>
                    <td class="text-center">{{ $customer->orders_count }}</td>
                    <td class="text-right">
                        ${{ number_format($customer->total_spent, 2) }}
                    </td>
                    <td class="text-center">
                        @if($customer->total_spent > 1000)
                            <span class="vip">YES</span>
                        @else
                            No
                        @endif
                    </td>
                    <td>
                        {{ $customer->created_at->format('Y-m-d') }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" class="text-center">
                        No customers found.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by E-Commerce Admin System
    </div>

</body>

</html>